apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmsa-projects-deployment
spec:
  selector:
    matchLabels:
      app: lmsa-projects-pod
  template:
    metadata:
      labels:
        app: lmsa-projects-pod
    spec:
      containers:
        - name: lmsa-projects-container
          image: lmsa01.azurecr.io/lmsa-projects:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mssql-connection-configmap
                  key: db-connection-string
